security:
    providers:
        api_token_provider:
            entity:
                class: App\Entity\User
                property: apiToken

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator

    access_control:
        - { path: ^/api, roles: ROLE_USER }
